# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160308_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='app.Category'),
        ),
    ]
